### ISSUE TITLE
多进程环境广播问题

### ISSUE THREAD

**Issue by gliheng** [yongbo000/egg-eventsource#1]
你好，生产环境node基本都是多进程的。这样EventSource只能推送给当前进程的客户。一个agent里面的agent.eventSource.broadcast可能更好用。现在我只能先通过agent  sendToApp。

**Comment by yongbo000** [comment]
已经更新该问题  @gliheng 

// 向全部worker线程推送
app.eventsource.sendToAllWorkers('this is an test message');

**Comment by gliheng** [comment]
谢谢
